# Lines configured by zsh-newuser-install
# lo
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt autocd
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/vineet/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Note: .profile is sourced via .zprofile. .profile contains
# $PATH exports.

# Set zsh prompt
autoload -Uz promptinit
promptinit
prompt off
prompt bart cyan cyan

# Set terminal colors
# Comment out to use tmux-256color when tmux started before zsh
# TERM=xterm-256color

alias ls="ls --color"

clear

source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# import gcloud settings
if [ -f "$HOME/.gcloudrc" ]; then 
        source "$HOME/.gcloudrc";
fi

# Python virtual environment settings
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/_work/projects
if [ -f "/usr/bin/virtualenvwrapper.sh" ]; then
        source "/usr/bin/virtualenvwrapper.sh";
fi

