# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/vineet/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Note: .profile is sources via .zprofile. .profile contains
# $PATH exports.

# Set zsh prompt
autoload -Uz promptinit
promptinit
prompt adam2

alias ls="ls --color"
